name = "ClevErr"
uuid = "6494cbee-9b15-41ee-8859-ec265d95f34c"
authors = ["Michael Schilling"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
